-- 코드를 입력하세요
SELECT MEMBER_ID
    , MEMBER_NAME
    , GENDER 
    ,TO_CHAR(DATE_OF_BIRTH,'YYYY-MM-DD') DATE_OF_BIRTH
    FROM MEMBER_PROFILE
    WHERE GENDER='W'
    AND TLNO IS NOT NULL
    AND extract (month from DATE_OF_BIRTH)=3
    ORDER BY MEMBER_ID   
;