-- 코드를 입력하세요
SELECT BOOK_ID
    ,TO_CHAR(PUBLISHED_DATE,'YYYY-MM-DD') PUBLISHED_DATE
    from BOOK
    where extract (year from PUBLISHED_DATE)=2021
    AND CATEGORY='인문'
    ORDER BY PUBLISHED_DATE
   
;